services:
  mongo:
    image: mongo:4.0
    restart: always
    expose:
    - 27017
    network_mode: 'host'
  server:
    build:
      context: .
    command: npm start
    network_mode: 'host'
    environment:
      IGNORE: '?'
      # CANVAS_API_TOKEN: 'put the token here'
      # CANVAS_URL: 'put the url here'
      # CANVAS_COURSE_ID: 'put the course id here'
    volumes:
      - ./src:/usr/app/src:rw

version: '3.6'
